title = "BuildAPizzeria"  # From Git
gitRepoUrl = "https://github.com/SlimeySnufs/BuildAPizzeria" # From Git

gitSourceBranch = "master"
changelog = true

[[classOrder]]
section = "Server"
classes = ["Data Manipulation","Data Replication","Moneypad Service"]

[[classOrder]]
section = "Utils"
classes = ["Signal","Connection"]
tag = "Lib"

[[classOrder]]
section = "Data Manipulation"
tag = "DataManipulation"

[[classOrder]]
section = "Data Replication"
tag = "DataReplication"

[[classOrder]]
section = "Moneypad Service"
tag = "MoneypadService"

[[classOrder]]
section "Client Data"
tag = "ClientData

[[classOrder]]
section = "Signal"
tag = "Signal"

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

# From git:
organizationName = "Slimey"
projectName = "BuildAPizzeria"
url = "https://AuthorName.github.io"
baseUrl = "/BuildAPizzeria"
tagline = "hopefully this sees light"

[footer]
style = "dark"
copyright = "Copyright Â© 2025 Slimey."
